# Uncomment this line to define a global platform for your project

platform :ios, '9.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

inhibit_all_warnings!

target ‘podTest’ do
    pod 'EasyReact'
    pod 'cokit'
    pod 'coobjc'
    pod 'SwiftMonkeyPaws', '~> 2.1.0'
end

target 'podTestUITests' do
    pod 'SwiftMonkey', '~> 2.1.0'
end

use_frameworks!
